nss-day-cohort-54/rare-v2-client-ghost

src/components/categories/AllCategories.js
src/components/categories/CategoryManager.js
src/components/categories/CreateCategoryForm.js

Added "add category" functions on server and client side
Fixes #6 

working add category page

---

src/components/ApplicationViews.js
src/components/categories/AllCategories.js
src/components/categories/CreateCategoryForm.js
src/components/tags/AllTags.js
src/components/tags/CreateTagForm.js
src/components/tags/TagManager.js

added feature to view and create tags
Fixes #8

Ndt create a tag

---

src/components/posts/AllPosts.js
src/components/posts/Post.js
src/components/users/UserManager.js

Updated posts.js to get all posts - displaying title, author, category, and date for now.
Fixes # 12

updated posts.js to display all posts

---

src/components/comments/CommentsList.js
src/components/posts/Post.js

When you click on an individual post it allows you to see all the details of that post
Fixes #5
Title
Header image (if exists)
Content
Publication date (MM/DD/YYYY)
Author's Display Name

view post details

---

src/components/ApplicationViews.js
src/components/posts/CreatePosts.js
src/components/posts/Post.js
src/components/posts/PostManager.js

Updated post model and fixtures to include approved and image_url. Added a create post in views. Client now has working form and content in createpost.js.
Fixes # 9

Jeh post create

---

src/components/buttonControls/ButtonControls.js
src/components/posts/MyPosts.js
src/components/posts/Post.js
src/components/posts/PostManager.js

Posts delete now
Fixes # (issue)
- Bug fix (non-breaking change which fixes an issue)

Rlt delete post

---

src/components/buttonControls/ButtonControls.js
src/components/tags/AllTags.js
src/components/tags/TagManager.js

tags list now shows buttons for admin and admin can delete tags
Fixes # 13/18

tags delete in order

---

src/components/ApplicationViews.js
src/components/auth/Register.js
src/components/posts/Post.js
src/components/tags/AllTags.js

fixed a bug surrounding currentUser on Posts and My Posts
Fixes # (issue)
- Bug fix (non-breaking change which fixes an issue)

Ndt add a tag to post

---

src/components/ApplicationViews.js
src/components/buttonControls/ButtonControls.js
src/components/comments/CommentsList.js
src/components/posts/AllPosts.js
src/components/posts/CreatePosts.js
src/components/posts/MyPosts.js
src/components/posts/Post.js
src/components/posts/PostManager.js

Added to CreatePosts.js and edit post feature should now work for the current user to edit their own posts.
Fixes # 15

added edit post features

---

src/components/ApplicationViews.js
src/components/posts/CreatePosts.js
src/components/posts/MyPosts.js

Non-admin posts are initially unapproved. Admin posts are approved
Fixes #24 

non admins post are unapproved. Admin posts are approved

---

src/components/comments/Comment.js
src/components/comments/CommentForm.js
src/components/comments/CommentsList.js

User should now see comments listed for individual post details. View Comments button in post details displays this from client. 
Fixes # 21

Jeh post comments

---

src/components/ApplicationViews.js
src/components/buttonControls/ButtonControls.js
src/components/comments/Comment.js
src/components/comments/CommentManager.js
src/components/comments/CommentsList.js
src/components/posts/AllPosts.js
src/components/posts/MyPosts.js
src/components/posts/Post.js
src/components/posts/PostsByUser.js
src/components/posts/SinglePost.js
src/components/posts/SubbedPosts.js

User who left a comment on a pos should now see button to delete and can delete their own comments.
Fixes # 22

Jeh delete comment

---

src/components/ApplicationViews.js
src/components/users/User.js
src/components/users/UserButtonControl.js
src/components/users/UserList.js
src/components/users/UserManager.js

Admin can now approve or disable users from user list
Fixes # 28

Rlt approve users

---

src/components/users/DeactivatedUsers.js
src/components/users/User.css
src/components/users/User.js
src/components/users/UserButtonControl.js
src/components/users/UserList.js

deactivated users button in users list shows deactivated users
Fixes # 29

deactivate users button shows deactivated users

---

src/UserContext.js
src/components/ApplicationViews.js
src/components/Rare.js
src/components/categories/AllCategories.js
src/components/comments/CommentsList.js
src/components/nav/NavBar.js
src/components/posts/AllPosts.js
src/components/posts/CreatePosts.js
src/components/posts/MyPosts.js
src/components/posts/Post.js
src/components/posts/PostManager.js

admins see a list of unapproved posts and can approve them
users only see approved posts
Fixes #25

Ndt admins can approve

---

src/components/Rare.js
src/components/categories/AllCategories.js
src/components/categories/CreateCategoryForm.js
src/components/posts/AllPosts.js
src/components/posts/CreatePosts.js
src/components/posts/MyPosts.js
src/components/posts/PostManager.js
src/components/tags/CreateTagForm.js

You can now filter posts by category
Fixes #34

filtering posts by category working

---

src/CommentStateContext.js
src/components/ApplicationViews.js
src/components/Rare.js
src/components/buttonControls/ButtonControls.js
src/components/comments/Comment.js
src/components/comments/CommentForm.js
src/components/comments/CommentManager.js
src/components/comments/CommentsList.js

User can now edit comments when viewing post details and clicking view comments. Edit button only appears for current user's comments.
Fixes # 23

Jeh edit comment

---

src/components/posts/AllPosts.js
src/components/posts/PostManager.js

search all posts by title or tag
Fixes #44
Fixes #46 

search all posts by tag or title

---

src/components/categories/AllCategories.js
src/components/categories/CreateCategoryForm.js
src/components/posts/Post.js
src/components/tags/AllTags.js
src/components/users/SubForm.js
src/components/users/SubManager.js
src/components/users/User.js

User can now view a user profile and subscribe to the author.
Fixes # 31

subscriber button works in user view

---

src/components/users/User.js
src/components/users/UserManager.js

lets user add profile photo
Fixes #40

Ndt upload user image
